export const AUTH_OTP_VERFICATION = 'AUTH_OTP_VERFICATION';
export const AUTH_OTP_VERFICATION_FAILED = 'AUTH_OTP_VERFICATION_FAILED';
export const AUTH_OTP_VERFICATION_SUCCESS = 'AUTH_OTP_VERFICATION_SUCCESS';

export const AUTH_OTP_SEND = 'AUTH_OTP_SEND';
export const AUTH_OTP_SEND_FAILED = 'AUTH_OTP_SEND_FAILED';
export const AUTH_OTP_SEND_SUCCESS = 'AUTH_OTP_SEND_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const AUTH_FORGOT_PASSWORD_OTP = 'AUTH_FORGOT_PASSWORD_OTP';
export const AUTH_FORGOT_PASSWORD_OTP_FAILED = 'AUTH_FORGOT_PASSWORD_OTP_FAILED';
export const AUTH_FORGOT_PASSWORD_OTP_SUCCESS = 'AUTH_FORGOT_PASSWORD_OTP_SUCCESS';

export const AUTH_RESET_PASSWORD_FAILED = 'AUTH_RESET_PASSWORD_FAILED';
export const AUTH_RESET_PASSWORD_SUCCESS = 'AUTH_RESET_PASSWORD_SUCCESS';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_CLEAR = 'AUTH_LOGOUT_CLEAR';

export const GET_LOGGED_IN_USER_INFO_SUCCESS = 'GET_LOGGED_IN_USER_INFO_SUCCESS';
export const GET_LOGGED_IN_USER_INFO_FAILED = 'GET_LOGGED_IN_USER_INFO_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';

export const EMPTY_CART = 'EMPTY_CART';
export const GET_CART = 'GET_CART';

export const SAVE_FRONT_DESIGN = 'SAVE_FRONT_DESIGN';
export const SAVE_BACK_DESIGN = 'SAVE_BACK_DESIGN';

export const FETCH_STORE_SUCCESS = 'FETCH_STORE_SUCCESS';
export const FETCH_STORE_FAILED = 'FETCH_STORE_FAILED';

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

export const GET_PRICING_SUCCESS = 'GET_PRICING_SUCCESS';
export const GET_PRICING_FAILED = 'GET_PRICING_FAILED';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const GENERAL_RESET = 'GENERAL_RESET';
export const SAVE_THEME_COLOR = 'SAVE_THEME_COLOR';

export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILED = 'FETCH_ALL_PRODUCTS_FAILED';

export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILED = 'CREATE_VENDOR_FAILED';

export const UPDATE_SELECTED_VARIANTS = 'UPDATE_SELECTED_VARIANTS';

export const GET_SELECTED_VARIANTS = 'GET_SELECTED_VARIANTS';

export const UPDATE_FRONT_CANVAS_SHAPE = 'UPDATE_FRONT_CANVAS_SHAPE';
export const UPDATE_BACK_CANVAS_SHAPE = 'UPDATE_BACK_CANVAS_SHAPE';
export const UPDATE_CANVAS_MODE = 'UPDATE_CANVAS_MODE';
