export const AUTH_OTP_VERFICATION = 'AUTH_OTP_VERFICATION';
export const AUTH_OTP_VERFICATION_FAILED = 'AUTH_OTP_VERFICATION_FAILED';
export const AUTH_OTP_VERFICATION_SUCCESS = 'AUTH_OTP_VERFICATION_SUCCESS';
