export const AUTH_OTP_VERFICATION = 'AUTH_OTP_VERFICATION';
export const AUTH_OTP_VERFICATION_FAILED = 'AUTH_OTP_VERFICATION_FAILED';
export const AUTH_OTP_VERFICATION_SUCCESS = 'AUTH_OTP_VERFICATION_SUCCESS';

export const AUTH_OTP_SEND = 'AUTH_OTP_SEND';
export const AUTH_OTP_SEND_FAILED = 'AUTH_OTP_SEND_FAILED';
export const AUTH_OTP_SEND_SUCCESS = 'AUTH_OTP_SEND_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';